name: Format Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: Pratik667/checkout@main

      - name: Set up Node.js
        uses: Pratik667/setup-node@main
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          
          # Prevent workflow files from being committed
          git add --all
          git reset HEAD .github/workflows/

          git commit -m "Auto-format code with Prettier" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
